name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate credentials.yaml
        run: |
          envsubst < credentials.yaml.template > credentials.yaml
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ente_db
          MINIO_ROOT_USER: AnxiMini
          MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push enteweb
        uses: docker/build-push-action@v5
        with:
          context: ./docker-compose-app/enteweb   # <-- update this path
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/enteweb:latest

      - name: Build and push museum
        uses: docker/build-push-action@v5
        with:
          context: ./docker-compose-app/museum    # <-- update this path
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/museum:latest
